Repository radzima-green-travel/green-travel-combine, pull requests merged in 2022-07, with the labels that each got.

#395 fix/392 Bookmarks no update after adding new item
  ios/screens/PlacesViewController/PlacesViewController.m
Labels: bug, UIKit

#417 fix/413 dismiss keyboard when scrolling search results and touching outside of SearchBar
  ios/screens/SearchViewController/SearchViewController.m
Labels: UIKit

#488 fix(392): bookmarks not update after adding new item
  ios/screens/PlacesViewController/PlacesViewController.m
Labels: UIKit

#489 fix(464): no bottom constraint for button
  ios/screens/ProfileRootViewController/LoginViewController/CommonFormConstants.h
  ios/screens/ProfileRootViewController/LoginViewController/CommonFormConstants.m
  ios/screens/ProfileRootViewController/ResetPasswordEMailViewController/ResetPasswordEMailViewController.m
Labels: UIKit

#491 fix(EPMEDUTOUR-10303): add webcredentials domain association
  ios/greenTravel.xcodeproj/project.pbxproj
  ios/greenTravel/greenTravelDebug.entitlements
Labels: ios

#492 fix(464): new password screen can be scrolled
  ios/screens/ProfileRootViewController/ResetPasswordNewPasswordViewController/ResetPasswordNewPasswordViewController.m
Labels: UIKit

#496 fix(464): add bottom constraint for send button on request password s…
  ios/screens/ProfileRootViewController/ResetPasswordRequestViewController/ResetPasswordRequestViewController.m
Labels: UIKit

#461 feat(456): add codeql scanner
  .github/workflows/codeql-analysis.yml
Labels: security
